apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wallabag

resources:
- namespace.yaml
- pvc.yaml
- redis-deployment.yaml
- redis-service.yaml
- postgres-deployment.yaml
- postgres-service.yaml
- wallabag-deployment.yaml
- wallabag-service.yaml
- external-secrets.yaml
- tailscale-ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: wallabag
