apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stirling-pdf

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - tailscale-ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
