apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paperless-ngx

resources:
- namespace.yaml
- pvc.yaml
- redis-deployment.yaml
- redis-service.yaml
- postgres-deployment.yaml
- postgres-service.yaml
- tika-deployment.yaml
- tika-service.yaml
- gotenberg-deployment.yaml
- gotenberg-service.yaml
- paperless-deployment.yaml
- paperless-service.yaml
- external-secrets.yaml
- tailscale-ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: paperless-ngx
