apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shared-services

resources:
- namespace.yaml
- pvc.yaml
- postgres-configmap.yaml
- postgres-deployment.yaml
- postgres-service.yaml
- redis-deployment.yaml
- redis-service.yaml
- external-secrets.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: shared-services
