apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - argocd-install.yaml
  - external-secrets.yaml

patches:
  - path: argocd-cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
  - path: argocd-rbac-cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-rbac-cm
  - path: argocd-server-service-patch.yaml
    target:
      kind: Service
      name: argocd-server

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
