apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: miniflux

resources:
- namespace.yaml
- pvc.yaml
- postgres-deployment.yaml
- postgres-service.yaml
- miniflux-deployment.yaml
- miniflux-service.yaml
- external-secrets.yaml
- tailscale-ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: miniflux
